plugins {
    id 'com.android.application'
}

android {
    namespace 'com.repkap11.repframe'
    compileSdk = 37

    defaultConfig {
        applicationId "com.repkap11.repframe"
        minSdk 23
        targetSdk 37
        versionCode 7
        versionName Integer.toString(versionCode)

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    signingConfigs {
        release {
            storePassword file('RuneTrackKeyStorePassword').text.trim()
            keyAlias "Repkap11"
            keyPassword file('RuneTrackKeyStorePassword').text.trim()
            storeFile file('RuneTrackKeyStore')
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }
    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "RepFrame_" + variant.versionName + ".apk"
        }
    }
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding true
        buildConfig true
    }


}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.preference:preference:1.2.1'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'
    implementation 'com.github.bumptech.glide:glide:5.0.9'
    annotationProcessor 'com.github.bumptech.glide:compiler:5.0.9'
    implementation 'com.github.msisuzney.GlideHeifDecoder:heifdecoder:0.5'
    implementation 'androidx.media3:media3-exoplayer:1.11.1'
    implementation 'androidx.media3:media3-ui:1.11.1'
}
